### ISSUE TITLE
Has anybody tried porting this to 5.3?

### ISSUE THREAD

**Issue by illuminate3** [BeatSwitch/lock-laravel#41]
Just wondering if anybody has ported this to 5.3? Or even if it was worth the trouble to attempt it?

**Comment by driesvints** [comment]
I'll try to see what I can do later this evening. Please note that I'm not maintaining this atm so use at your own risk.

**Comment by driesvints** [comment]
@illuminate3 can you try out this branch: #42

If it works then I'll merge it in and tag it with a new release.

**Comment by illuminate3** [comment]
Thanks, I'll give it a shot.

**Comment by driesvints** [comment]
It's a development version and you're probably (standard composer) requiring stable packages.

Try `"beatswitch/lock-laravel": "dev-master@dev"`

**Comment by driesvints** [comment]
@illuminate3 ugh sorry. You need to reference this branch of course:

`"beatswitch/lock-laravel": "dev-update-to-latest-laravel@dev"

**Comment by illuminate3** [comment]
ugh, I missed the "dev-" part when I tried that bit.

composer let me install this. I'm gonna play around with your package and see if I come up with any issues.

Thanks!

**Comment by xLink** [comment]
@illuminate3 did you get any further with this?

**Comment by xLink** [comment]
Ok, i had a look into this, after having to add `->all()` to all my fluent queries cause of a change they made in Laravel, I've got another issue where the `if ($app['auth']->check()) {` is never being set to true even when I'm logged in(and debugbar can see it)

Offending Code:
https://github.com/BeatSwitch/lock-laravel/blob/master/src/LockServiceProvider.php#L80

After doing some googling, best I've seen is to move that auth()->check() into a middleware and register it after the `Middleware\StartSession`, but there's got to be more to it than that...

**Comment by driesvints** [comment]
@xLink I'll try to update the PR with a middleware bootstrap like the one proposed in #31.

**Comment by driesvints** [comment]
I actually also want to drop support for PHP 5.6 since it ends in a few days: http://php.net/supported-versions.php

**Comment by xLink** [comment]
Awesome ill test that out in my own setup see if it helps the cause any :D

**Comment by driesvints** [comment]
@xLink try it: https://github.com/BeatSwitch/lock-laravel/pull/42

I'll probably drop 5.6 support in the minor version after the next one.

**Comment by xLink** [comment]
@driesvints ok testing it out, you on slack or something?

**Comment by xLink** [comment]
ok @driesvints got it all setup and running, still got a weird issue with the authenticated user not being passed through in the service provider so Lock doesn't know anything about it

**Comment by driesvints** [comment]
Related to #29?

**Comment by xLink** [comment]
Dont think so that fix is already in the code, i think its a change with L5.3's auth somewhere, might even be 5.2?

**Comment by driesvints** [comment]
Ok so I made a bunch more changes. The middleware is now only needed if you want to use the `LockAware` trait. Everything else should work out of the box.

You cannot set use permissions anymore through the permissions config option anymore. That didn't make much sense anyway...

**Comment by xLink** [comment]
Seems to be working now, the only change i'd make is...

in the `lock.php` config
`    'driver' => BeatSwitch\Lock\Integrations\Laravel\DatabaseDriver::class,`

make that the class ref instead of the "driver name"

and then in your `LockServiceProvider`
```
    /**
     * Returns the configured driver.
     *
     * @return \BeatSwitch\Lock\Drivers\Driver
     */
    private function driver()
    {
        // obtain the driver details
        $driver = config('lock.driver', null);

        // If the user choose the persistent database driver, bootstrap
        // the database driver with the default database connection.
        if ($driver !== null) {
            return new $driver($this->app['db']->connection(), config('lock.table'));
        }

        // Otherwise use the static array driver.
        return new ArrayDriver();
    }
```

add the necessary config option back so we don't need to extend the class and override the method to get our custom driver in there(which seems to be failing now that you moved the methods to private? this request fixes the issue though) 

As previously mentioned, thanks so much for helping fix up for 5.3 I know you have everywhere that its unmaintained, but it's the only thing that I want to use xD

**Comment by xLink** [comment]
Should probably mention that you called user()->user() in the middleware too...
```php
            $lock = $this->manager->caller(Auth::user()->user());
```

need to take one of them off..

i was also gonna try and add the fixes to the pull request but no idea how :D

**Comment by driesvints** [comment]
Made some final changes for the 0.5 release. I renamed the middleware to `InitLockAwareTrait` so it makes more sense on what it does. I also made the methods in the Service Provider protected again so you can override them.

@xLink I don't want to change the behavior for the `driver` config option because that would imply that the class always gets resolved from the IoC and that you can't bootstrap the dependencies for the class anymore. I've made the methods protected again so you can overwrite them easily but I think I'm gonna take a look at setting it up with Laravel's manager system in the future.

Anyway, I hope this sufficient for a new release :)

**Comment by driesvints** [comment]
0.5.0 is now available.
